In [93]:
import pandas
pandas.__version__

'0.23.4'

In [94]:
import pandas as pd
import numpy as np

#### $Объект$ *Series*

Series как обобщенный массив Numpy

In [95]:
data = pd.Series([0.25, .5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [96]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [97]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [98]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64


In [99]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [100]:
data['b']

0.5

In [101]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                index=['2', 5, 3, '7'])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [102]:
data[2]

0.75

In [103]:
data['2']

0.25

In [104]:
data[3]

0.75

*Series как специализированный словарь*

In [105]:
population_dict = {'California': 3832521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135
}
population = pd.Series(population_dict)
population

California     3832521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [106]:
population['California']

3832521

In [107]:
population['California': 'Florida']

California     3832521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

*Создание объектов Series*

In [108]:
# pd.Series(data, index=index)
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [109]:
pd.Series(5, index=[100, 200, 300, 450])

100    5
200    5
300    5
450    5
dtype: int64

In [110]:
# ключи не отсортированы
p = pd.Series({2:'a', 1:'b', 3:'c'})
p

2    a
1    b
3    c
dtype: object

In [111]:
# ключи отсортированы
p.sort_index()

1    b
2    a
3    c
dtype: object

In [112]:
# значения отсортированы
p.sort_values()

2    a
1    b
3    c
dtype: object

In [113]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3,2])

3    c
2    a
dtype: object

#### $Объект$ *DataFrame*

In [114]:
area_dict = {'California': 423967,
            'Texas': 695662,
            'New York': 141297,
            'Florida': 170312,
            'Illinois': 149995
}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [115]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California     3832521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [116]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [117]:
states.values

array([[ 3832521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]], dtype=int64)

In [118]:
states.columns

Index(['population', 'area'], dtype='object')

*DataFrame как специализированный словарь*

In [119]:
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

*Создание объектов DataFrame*

In [120]:
# из одного объекта Series
population

California     3832521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [121]:
pd.DataFrame(population, columns=['population'])

population
California     3832521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [122]:
# из списка словарей
data = [{'a':i, 'b': i * 2} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [123]:
# Pandas умеет заполнять пропущенный значения значениями Nan
pd.DataFrame([{'a':1, 'b': 2}, {'b':3, 'c':4}, {'f':10}])

a    b    c     f
0  1.0  2.0  NaN   NaN
1  NaN  3.0  4.0   NaN
2  NaN  NaN  NaN  10.0

In [124]:
# из словарz объектов Series
pd.DataFrame({'population': population, 'area': area})

population    area
California     3832521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [125]:
print(type(population))
print(type(area))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [126]:
# из двумерного массива NumPy
pd.DataFrame(np.random.rand(3,2),
            columns = ['foo', 'bar'],
            index = ['a', 'b', 'c'])

foo       bar
a  0.156439  0.649874
b  0.082979  0.172511
c  0.775725  0.336139

In [127]:
np.random.rand(3,2)

array([[0.57978741, 0.58855301],
       [0.07473966, 0.97298357],
       [0.3691085 , 0.11871578]])

In [128]:
# из структурированного массива NumPy
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [129]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

*Объект Index*

In [130]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

Объект Index как неимзеняемый массив

In [131]:
ind[1]

3

In [132]:
ind[::2] #через один

Int64Index([2, 5, 11], dtype='int64')

In [133]:
print(ind.size)
print(ind.shape)
print(ind.ndim) # Number of array dimensions
print(ind.dtype)

5
(5,)
1
int64


In [134]:
# нельзя вот так просто изменить значение
ind[1] = 0

TypeError: Index does not support mutable operations

*Объект Index как упоряоченное множество*

In [135]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [136]:
indA & indB # пересечение

Int64Index([3, 5, 7], dtype='int64')

In [137]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [138]:
indA | indB # объединение

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [139]:
indA ^ indB # симметричная разность: оставляем все кроме повторяющихся элементов

Int64Index([1, 2, 9, 11], dtype='int64')

*Индексация и выборка данных*

*Выборка данных из Series*

*Объект Series как словарь*

In [140]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [141]:
data['b']

0.5

In [142]:
'a' in data

True

In [143]:
0.25 in data

False

In [144]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [145]:
data.values()

TypeError: 'numpy.ndarray' object is not callable

In [146]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [147]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [148]:
data.get('c')

0.75

In [149]:
data.get('f')

In [150]:
data.get('f', 100)

100

In [151]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

*Объект Series как одномерный массив*

In [152]:
#срез посредством явного индекса
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [153]:
#срез посредством неявного целочиленного индекса
data[0:2]

a    0.25
b    0.50
dtype: float64

In [154]:
#маскирование 
data[(data>0.3) & (data<0.9)]

b    0.50
c    0.75
dtype: float64

In [155]:
# прихотливая индексация
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

*Индексаторы loc, iloc, ix*

In [156]:
data = pd.Series(['a','b','c'], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [157]:
# использование явного индекса при индексации
data[1]

'a'

In [158]:
# использование неявного индекса при срезе
data[1:3]

3    b
5    c
dtype: object

loc помогает делать индексацию при помощи явного индекса

In [159]:
data.loc[1]

'a'

In [160]:
data.loc[1:3]

1    a
3    b
dtype: object

iloc помогает выполнить индексацию и срезы по неявным индексам

In [161]:
data.iloc[1]

'b'

In [162]:
data.iloc[1:3]

3    b
5    c
dtype: object

ix - гибрид loc + iloc. Эквивалент обычной индексации []

#### *Выборка данных из DataFrame*

*DataFrame как соварь*

In [163]:
area = pd.Series({'California': 423967,
            'Texas': 695662,
            'New York': 141297,
            'Florida': 170312,
            'Illinois': 149995})
             
pop = pd.Series({'California': 3832521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135})

In [164]:
data = pd.DataFrame({'area': area, 'pop': pop})
data

area       pop
California  423967   3832521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [165]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [166]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [167]:
data['area'] is data.area

True

In [168]:
data.pop is data['pop'] # имя столбца конфликтует с названием метода pop()

False

In [169]:
# добавление столбца
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967   3832521    9.039668
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [170]:
data.sort_index()

area       pop     density
California  423967   3832521    9.039668
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

*DataFrame как двумерный массив*

In [171]:
data.values

array([[4.23967000e+05, 3.83252100e+06, 9.03966818e+00],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [172]:
data.T # транспонирование

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.832521e+06  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.039668e+00  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [173]:
data.values[0]

array([4.23967000e+05, 3.83252100e+06, 9.03966818e+00])

In [174]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [175]:
data.T.iloc[:3,:2] # неявные индексы

California         Texas
area     4.239670e+05  6.956620e+05
pop      3.832521e+06  2.644819e+07
density  9.039668e+00  3.801874e+01

In [176]:
data.T.loc[:'density',:'Texas'] # явные индексы

California         Texas
area     4.239670e+05  6.956620e+05
pop      3.832521e+06  2.644819e+07
density  9.039668e+00  3.801874e+01

In [177]:
data.T.ix[:3,:'Texas'] # те и другие

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


California         Texas
area     4.239670e+05  6.956620e+05
pop      3.832521e+06  2.644819e+07
density  9.039668e+00  3.801874e+01

In [178]:
# в индикаторе loc млжно сочетать маскирование и прихотливую индексацию
data.loc[data['density'] > 100, ['pop', 'area']]

pop    area
New York  19651127  141297
Florida   19552860  170312

In [179]:
# изменение значения
data.iloc[0:2, -1] = 90

In [180]:
data

area       pop     density
California  423967   3832521   90.000000
Texas       695662  26448193   90.000000
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

*Дополнительный синтаксис дл индексации*

In [181]:
data['California': 'New York']

area       pop     density
California  423967   3832521   90.000000
Texas       695662  26448193   90.000000
New York    141297  19651127  139.076746

In [182]:
data[0:3]

area       pop     density
California  423967   3832521   90.000000
Texas       695662  26448193   90.000000
New York    141297  19651127  139.076746

In [183]:
data[data.density == 90]

area       pop  density
California  423967   3832521     90.0
Texas       695662  26448193     90.0

### Операции над данными

*Универсальные функции: сохранение индекса*

In [184]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4)) # randint(0,10,4) - 4 числа от нуля до 10
ser

0    6
1    3
2    7
3    4
dtype: int32

In [185]:
df = pd.DataFrame(rng.randint(0,10, (3,4)), columns = ['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [186]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [187]:
np.sin(df*np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

*Универсальные функции: выравнивание индексов*

*Выравание индексов в объектах Series*

In [188]:
area = pd.Series({'Alaska':1723337,'Texas': 695662, 'California': 423967,}, name='area')
population = pd.Series({'Texas': 2644193, 'California': 38332521, 'New York':19651127}, name='population')

In [189]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas          3.800974
dtype: float64

In [190]:
# объединение индексов
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [191]:
# отсутствующие значения заполняются Nan
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [192]:
A.add(B)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [193]:
A.add(B, fill_value = 1000)

0    1002.0
1       5.0
2       9.0
3    1005.0
dtype: float64

In [194]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

*Выравание индексов в объектах DataFrame*

In [195]:
list('ABC')

['A', 'B', 'C']

In [196]:
A = pd.DataFrame(rng.randint(0,20, (2,2)),
                columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [197]:
B = pd.DataFrame(rng.randint(0,10, (3,3)),
                columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [198]:
A+B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [199]:
A.add(B, fill_value = 0)

A     B    C
0   1.0  15.0  9.0
1  13.0   6.0  0.0
2   2.0   9.0  6.0

In [200]:
fill = A.stack().mean()
fill

4.5

In [201]:
A.stack()

0  A     1
   B    11
1  A     5
   B     1
dtype: int32

In [202]:
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [203]:
A.mul(B) # умножение

A     B   C
0   0.0  44.0 NaN
1  40.0   5.0 NaN
2   NaN   NaN NaN

*Универсальные функции: выполнение операции между DataFrame и Series*

In [204]:
A = rng.randint(10, size = (3,4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [205]:
A[0]

array([3, 8, 2, 4])

In [206]:
A - A[0] # вычитание в NumPy происходит построчно

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [207]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [208]:
df - df.iloc[0]  # вычитание в Pandas происходит построчно

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [209]:
# если нужно построчно:
df.sub(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [210]:
halfrow = df.iloc[0, ::2] # [строка, все столбцы начиная с первого через один]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [211]:
df - halfrow # из всех значений столбца Q вычесть 0, из S вычесть единицы, по остальным данных нет

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

*Обработка отсутствующих данных*

In [212]:
vals1 = np.array([1, None, 3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [213]:
vals1.sum() # error

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

*Nan: отсутствующие числовые данные*

In [214]:
vals2 = np.array([1, np.nan, 3,4])
vals2.dtype

dtype('float64')

In [215]:
1 + np.nan

nan

In [216]:
0*np.nan

nan

In [217]:
vals2.sum(), vals2.min(), vals2.max()

C:\Users\User\Anaconda3\lib\site-packages\numpy\core\_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
C:\Users\User\Anaconda3\lib\site-packages\numpy\core\_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


(nan, nan, nan)

In [218]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2) # используйте функции NumPy

(8.0, 1.0, 4.0)

Nan - это всегда значения с плавающей точкой. Аналогов для str, int и других - нет.

*Значения Nan и None в Pandas*

In [219]:
pd.Series([1,np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [220]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [221]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

*Операции над пустыми значениями*

In [222]:
data = pd.Series([1, np.nan, 'hello', None])

In [223]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [224]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [225]:
data[data.notnull()]

0        1
2    hello
dtype: object

*Удаление пустых значений*

In [226]:
data.dropna()

0        1
2    hello
dtype: object

In [227]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]
    
])

df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [228]:
df.dropna() # удаляем по строкам

0    1  2
1  2.0  3.0  5

In [229]:
df.dropna(axis='columns') # удаляем по столбцам

2
0  2
1  5
2  6

In [230]:
# можно отбрасывать только строки/столцы с определенным кол-вом пропущенных значений
df.dropna(axis='columns', how = 'all') # отбрасываем те столбцы, где все nan

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [231]:
df[3] = np.nan

In [232]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [233]:
df.dropna(axis='rows', thresh = 3) # оставляем те строки, где непустых значений не менее 3

0    1  2   3
1  2.0  3.0  5 NaN

*Заполнение пустых значений*

In [234]:
data = pd.Series([1, np.nan, 2, None, 3], index = list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [235]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [236]:
# заполнение по направлению вперед (предыдущим значением)
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [237]:
# заполнение по направлению назад (впереди идущим значением)
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [238]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [239]:
df.fillna(method='ffill', axis=1) # значением в первом столбце осталось Nan

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0